name: Jest Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Navigate to the recipe-book directory
        run: cd recipe-book
      
      - name: run pwd command
        run: pwd

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm test:coverage